; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lilygo-t-display-s3]
platform = espressif32
board = lilygo-t-display-s3
framework = arduino
extra_scripts = pre:extra_script.py

build_flags =
    -I../../inc
    -I../../src
    -D_FREE_RTOS
    -DXCPLIB_CFG_OVERRIDE=\"xcplib_rtos_cfg.h\"
    ; Enable this on LilyGo T-Display-S3 compatible boards:
     -DOPTION_DISPLAY
    ; Set these locally, for example:
    ; -DWIFI_SSID=\"your-ssid\"
    ; -DWIFI_PASSWORD=\"your-password\"

upload_port = /dev/cu.usbmodem101
upload_speed = 460800
monitor_port = /dev/cu.usbmodem101
monitor_speed = 115200

lib_deps =
    lovyan03/LovyanGFX
